language: ruby
rvm:
- 2.5.1
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: "40eaf40f-8cc2-4656-a2fe-d88ce56a9535"

